### ISSUE TITLE
quick start message is not kind

### ISSUE THREAD

**Issue by misogihagi** [snowpackjs/rollup-plugin-polyfill-node#4]
hello. I came here because npm warn showed:
```
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
```

though this repository resolved my dependency problem, It may be better to display quickstart easy for beginners.

**Comment by FredKSchott** [comment]
I don't believe that we're using this dependency anymore! I don't see it in our package-lock, at least. Maybe this error is for a different rollup plugin?

**Comment by misogihagi** [comment]
Although this repository does not occur the npm warning, 
my `npm install rollup-plugin-node-polyfills`
outputs
`    "rollup-plugin-node-polyfills": {
      "version": "0.2.1",
      "resolved": "https://registry.npmjs.org/rollup-plugin-node-polyfills/-/rollup-plugin-node-polyfills-0.2.1.tgz",
      "integrity": "sha512-4kCrKPTJ6sK4/gLL/U5QzVT8cxJcofO0OU74tnB19F40cmuAKSzH5/siithxlofFEjwvw1YAhPmbvGNA6jEroA==",
      "dev": true,
      "requires": {
        "rollup-plugin-inject": "^3.0.0"
      }
    },
`
I think this problem arises from package publishing.

**Comment by FredKSchott** [comment]
We no longer use that package, if you upgrade to Snowpack latest you should be on `rollup-plugin-polyfill-node@^0.6.2` instead.

**Comment by misogihagi** [comment]
I got it!
<h2> NOT rollup-plugin-<b>node-polyfills<b/> but rollup-plugin-<b>polyfill-node</b>
I didn't notice. Thanks.
